[build]
builder = "NIXPACKS"
watchEdges = ["package.json"]
installCommand = "rm -rf node_modules package-lock.json && npm install"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
