[build]
builder = "NIXPACKS"
watchEdges = ["package.json", "prisma/schema.prisma"]
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm start"
restartPolicyType = "ON_FAILURE"
